on: [ push ]
name: tests
jobs:
  build_and_test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run tests for core
        run: |
          cargo test --release
          cargo test --benches
          cargo run --example n01_primitives 
          cargo run --example n02_boards 
          cargo run --example n03_place 
          cargo run --example n04_moves
